import Link from "next/link";
import { CalendarClock, Euro, MapPin, Users } from "lucide-react";
import { AppShell } from "@/components/dashboard/app-shell";
import { MetricCard } from "@/components/dashboard/metric-card";
import { StatusBadge } from "@/components/dashboard/status-badge";
import { getDashboardData } from "@/lib/dashboard";

const money = (cents: number) => new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR" }).format(cents / 100);
const date = (value: Date) => new Intl.DateTimeFormat("nl-NL", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(value);

export default async function DashboardPage() {
  const data = await getDashboardData();
  return <AppShell title="Bedrijfsdashboard" activePath="/dashboard"><div className="page-heading"><div><span className="eyebrow">{data.company.name}</span><h2>Goedemorgen, {data.session.userId ? data.company.contactName ?? "ondernemer" : "ondernemer"}</h2><p>Dit gebeurt er met je aanvragen en betalingen.</p></div><Link className="button primary" href="/dashboard/leads">Alle leads bekijken</Link></div><section className="metrics"><MetricCard label="Leads deze week" value={String(data.weekCount)} detail={`Minimum van ${data.company.minimumWeeklyLeads} per week`} icon={Users}/><MetricCard label="Leads deze maand" value={String(data.monthCount)} detail="Toegewezen aanvragen" icon={CalendarClock}/><MetricCard label="Leadkosten deze maand" value={money(data.monthCostCents)} detail="Facturabele toewijzingen" icon={Euro}/><MetricCard label="Actieve regio's" value={String(data.company.regions.length)} detail={data.company.regions.map(r => r.region).join(", ") || "Nog instellen"} icon={MapPin}/></section><div className="dashboard-grid"><section className="panel"><div className="panel-header"><h3>Recente leads</h3><Link className="panel-link" href="/dashboard/leads">Bekijk alles</Link></div>{data.recent.length ? <><div className="table-wrap desktop-table"><table><thead><tr><th>Datum</th><th>Naam</th><th>Categorie</th><th>Plaats</th><th>Prijs</th><th>Status</th><th></th></tr></thead><tbody>{data.recent.map(item => { const contact = item.lead.contact as {name?:string}; return <tr key={item.id}><td>{date(item.allocatedAt)}</td><td><strong>{contact.name ?? "Aanvrager"}</strong></td><td>{item.lead.category}</td><td>{item.lead.city ?? item.lead.postalCode}</td><td>{money(item.priceCents)}</td><td><StatusBadge>{item.companyStatus}</StatusBadge></td><td><Link className="panel-link" href={`/dashboard/leads/${item.leadId}`}>Bekijken</Link></td></tr>; })}</tbody></table></div></> : <div className="empty-state"><h3>Nog geen leads</h3><p>Zodra een aanvraag past, verschijnt die hier.</p></div>}</section><aside className="side-stack"><section className="panel progress-card"><span className="eyebrow">Weekafspraak</span><h3>{data.weekCount >= data.company.minimumWeeklyLeads ? "Minimum behaald" : "Nog onderweg"}</h3><p>{data.weekCount} van de afgesproken {data.company.minimumWeeklyLeads} leads ontvangen.</p><div className="progress-track"><div className="progress-bar" style={{width:`${Math.min(100, data.weekCount / data.company.minimumWeeklyLeads * 100)}%`}} /></div></section><section className="panel progress-card"><span className="eyebrow">SEPA-mandaat</span><h3>{data.mandate?.status ?? "Niet ingesteld"}</h3><p>Openstaand factuursaldo: {money(data.openCents)}.</p></section></aside></div></AppShell>;
}
