-- Created from prisma/schema.prisma. Apply through `npx prisma migrate deploy`.
CREATE TYPE "Role" AS ENUM ('COMPANY', 'ADMIN');
CREATE TYPE "ApiKeyStatus" AS ENUM ('ACTIVE', 'REVOKED');
CREATE TYPE "LeadStatus" AS ENUM ('NEW', 'MATCHED', 'ALLOCATED', 'CLOSED');
CREATE TYPE "AllocationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'INVOICED', 'DISPUTED', 'CREDITED');
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT', 'OPEN', 'PAID', 'VOID', 'UNCOLLECTIBLE');
CREATE TYPE "DisputeStatus" AS ENUM ('OPEN', 'UNDER_REVIEW', 'RESOLVED_COMPANY', 'RESOLVED_PLATFORM', 'REJECTED');
CREATE TYPE "AuditActorType" AS ENUM ('USER', 'API_KEY', 'SYSTEM', 'STRIPE');

CREATE TABLE "Company" ("id" UUID NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "stripeCustomerId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Company_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" UUID NOT NULL, "companyId" UUID, "email" TEXT NOT NULL, "name" TEXT, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'COMPANY', "sessionVer" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ApiKey" ("id" UUID NOT NULL, "companyId" UUID NOT NULL, "name" TEXT NOT NULL, "prefix" TEXT NOT NULL, "keyHash" TEXT NOT NULL, "hmacRequired" BOOLEAN NOT NULL DEFAULT false, "hmacSecretEncrypted" TEXT, "status" "ApiKeyStatus" NOT NULL DEFAULT 'ACTIVE', "lastUsedAt" TIMESTAMP(3), "expiresAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "revokedAt" TIMESTAMP(3), CONSTRAINT "ApiKey_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Lead" ("id" UUID NOT NULL, "sourceCompanyId" UUID NOT NULL, "sourceApiKeyId" UUID, "externalId" TEXT, "fingerprint" TEXT NOT NULL, "status" "LeadStatus" NOT NULL DEFAULT 'NEW', "category" TEXT NOT NULL, "postalCode" TEXT NOT NULL, "consentAt" TIMESTAMP(3) NOT NULL, "contact" JSONB NOT NULL, "attributes" JSONB NOT NULL DEFAULT '{}', "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Lead_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PricingRule" ("id" UUID NOT NULL, "companyId" UUID NOT NULL, "name" TEXT NOT NULL, "category" TEXT NOT NULL, "postalPrefixes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], "priceCents" INTEGER NOT NULL, "currency" CHAR(3) NOT NULL DEFAULT 'EUR', "priority" INTEGER NOT NULL DEFAULT 0, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PricingRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Allocation" ("id" UUID NOT NULL, "companyId" UUID NOT NULL, "leadId" UUID NOT NULL, "pricingRuleId" UUID, "status" "AllocationStatus" NOT NULL DEFAULT 'PENDING', "score" INTEGER NOT NULL, "priceCents" INTEGER NOT NULL, "currency" CHAR(3) NOT NULL DEFAULT 'EUR', "priceSnapshot" JSONB NOT NULL, "allocatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "acceptedAt" TIMESTAMP(3), "expiresAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Allocation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Invoice" ("id" UUID NOT NULL, "companyId" UUID NOT NULL, "stripeInvoiceId" TEXT, "status" "InvoiceStatus" NOT NULL DEFAULT 'DRAFT', "currency" CHAR(3) NOT NULL DEFAULT 'EUR', "subtotalCents" INTEGER NOT NULL DEFAULT 0, "taxCents" INTEGER NOT NULL DEFAULT 0, "totalCents" INTEGER NOT NULL DEFAULT 0, "periodStart" TIMESTAMP(3) NOT NULL, "periodEnd" TIMESTAMP(3) NOT NULL, "dueAt" TIMESTAMP(3), "paidAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InvoiceLine" ("id" UUID NOT NULL, "invoiceId" UUID NOT NULL, "allocationId" UUID NOT NULL, "description" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "unitCents" INTEGER NOT NULL, "totalCents" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InvoiceLine_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Dispute" ("id" UUID NOT NULL, "companyId" UUID NOT NULL, "allocationId" UUID NOT NULL, "openedByUserId" UUID, "status" "DisputeStatus" NOT NULL DEFAULT 'OPEN', "reason" TEXT NOT NULL, "notes" TEXT, "resolution" TEXT, "resolvedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Dispute_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" UUID NOT NULL, "companyId" UUID, "actorUserId" UUID, "actorApiKeyId" UUID, "actorType" "AuditActorType" NOT NULL, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "requestId" TEXT, "metadata" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "leadId" UUID, "allocationId" UUID, "invoiceId" UUID, "disputeId" UUID, CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StripeWebhookEvent" ("id" UUID NOT NULL, "eventId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "companyId" UUID, "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "processedAt" TIMESTAMP(3), CONSTRAINT "StripeWebhookEvent_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Company_slug_key" ON "Company"("slug");
CREATE UNIQUE INDEX "Company_stripeCustomerId_key" ON "Company"("stripeCustomerId");
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_companyId_idx" ON "User"("companyId");
CREATE UNIQUE INDEX "ApiKey_keyHash_key" ON "ApiKey"("keyHash");
CREATE INDEX "ApiKey_companyId_status_idx" ON "ApiKey"("companyId", "status");
CREATE UNIQUE INDEX "Lead_fingerprint_key" ON "Lead"("fingerprint");
CREATE UNIQUE INDEX "Lead_sourceCompanyId_externalId_key" ON "Lead"("sourceCompanyId", "externalId");
CREATE INDEX "Lead_status_category_postalCode_idx" ON "Lead"("status", "category", "postalCode");
CREATE INDEX "Lead_sourceCompanyId_receivedAt_idx" ON "Lead"("sourceCompanyId", "receivedAt");
CREATE INDEX "PricingRule_companyId_active_category_idx" ON "PricingRule"("companyId", "active", "category");
CREATE UNIQUE INDEX "Allocation_companyId_leadId_key" ON "Allocation"("companyId", "leadId");
CREATE INDEX "Allocation_companyId_status_allocatedAt_idx" ON "Allocation"("companyId", "status", "allocatedAt");
CREATE UNIQUE INDEX "Invoice_stripeInvoiceId_key" ON "Invoice"("stripeInvoiceId");
CREATE INDEX "Invoice_companyId_status_periodEnd_idx" ON "Invoice"("companyId", "status", "periodEnd");
CREATE UNIQUE INDEX "InvoiceLine_allocationId_key" ON "InvoiceLine"("allocationId");
CREATE INDEX "InvoiceLine_invoiceId_idx" ON "InvoiceLine"("invoiceId");
CREATE INDEX "Dispute_companyId_status_createdAt_idx" ON "Dispute"("companyId", "status", "createdAt");
CREATE INDEX "Dispute_allocationId_idx" ON "Dispute"("allocationId");
CREATE INDEX "AuditLog_companyId_createdAt_idx" ON "AuditLog"("companyId", "createdAt");
CREATE INDEX "AuditLog_entityType_entityId_createdAt_idx" ON "AuditLog"("entityType", "entityId", "createdAt");
CREATE UNIQUE INDEX "StripeWebhookEvent_eventId_key" ON "StripeWebhookEvent"("eventId");
CREATE INDEX "StripeWebhookEvent_companyId_receivedAt_idx" ON "StripeWebhookEvent"("companyId", "receivedAt");

ALTER TABLE "User" ADD CONSTRAINT "User_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_sourceCompanyId_fkey" FOREIGN KEY ("sourceCompanyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Lead" ADD CONSTRAINT "Lead_sourceApiKeyId_fkey" FOREIGN KEY ("sourceApiKeyId") REFERENCES "ApiKey"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PricingRule" ADD CONSTRAINT "PricingRule_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Allocation" ADD CONSTRAINT "Allocation_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Allocation" ADD CONSTRAINT "Allocation_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Allocation" ADD CONSTRAINT "Allocation_pricingRuleId_fkey" FOREIGN KEY ("pricingRuleId") REFERENCES "PricingRule"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InvoiceLine" ADD CONSTRAINT "InvoiceLine_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InvoiceLine" ADD CONSTRAINT "InvoiceLine_allocationId_fkey" FOREIGN KEY ("allocationId") REFERENCES "Allocation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_allocationId_fkey" FOREIGN KEY ("allocationId") REFERENCES "Allocation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Dispute" ADD CONSTRAINT "Dispute_openedByUserId_fkey" FOREIGN KEY ("openedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorUserId_fkey" FOREIGN KEY ("actorUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorApiKeyId_fkey" FOREIGN KEY ("actorApiKeyId") REFERENCES "ApiKey"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "Lead"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_allocationId_fkey" FOREIGN KEY ("allocationId") REFERENCES "Allocation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_disputeId_fkey" FOREIGN KEY ("disputeId") REFERENCES "Dispute"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "StripeWebhookEvent" ADD CONSTRAINT "StripeWebhookEvent_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
